// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emjtsxfjrprcrssuvbat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtanRzeGZqcnByY3Jzc3V2YmF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MDM4MTAsImV4cCI6MjA2ODE3OTgxMH0.uOZTnz5FyObUEzH6w6m3j2faA-RspxqwDopIypUWAzQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});